"""
Django settings for painel project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raiz do repositório (um nível acima de painel/) — onde fica o .env único.
REPO_DIR = BASE_DIR.parent
load_dotenv(REPO_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    'django-insecure-8s78^6j5y4w%d=em+^u))852vwx4bvr$98a7vwb#x4@wtjy0)3')

# Painel roda só local, sem exposição.
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'painel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'painel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Postgres via DATABASE_URL no .env (ex.: postgresql://user:senha@localhost:5432/paparazzi).
# Cai para sqlite só se DATABASE_URL não estiver definida (permite abrir sem o banco).
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# Controle do pipeline (mirror/cortes)
# ---------------------------------------------------------------------------
# Retenção: horas após a postagem até apagar o ARQUIVO local (metadados ficam).
RETENCAO_HORAS = int(os.getenv("RETENCAO_HORAS", "24"))

# Ollama (LLMs): serviço systemd e como encerrar/subir. O shutdown só ocorre
# quando não há consumidores ativos (watcher/coletor e poster).
OLLAMA_SYSTEMD_UNIT = os.getenv("OLLAMA_SYSTEMD_UNIT", "ollama.service")
OLLAMA_MODELOS = [m.strip() for m in os.getenv(
    "OLLAMA_MODELOS", os.getenv("LLM_MODEL", "qwen2.5:3b")).split(",") if m.strip()]

# Serviços systemd controlados pelo painel (liga/desliga).
WATCHER_SYSTEMD_UNIT = os.getenv("WATCHER_SYSTEMD_UNIT", "paparazzi-watcher.service")
POSTER_SYSTEMD_UNIT = os.getenv("POSTER_SYSTEMD_UNIT", "paparazzi-poster.service")

# Prefixo do systemctl. Serviços de sistema (ollama) controlados pelo usuário exigem
# uma regra polkit (ver systemd/README) — ou troque para ["sudo","systemctl"].
SYSTEMCTL = os.getenv("SYSTEMCTL", "systemctl").split()

# Diretório dos vídeos finais (para a retenção localizar/apagar arquivos).
MIRROR_OUTPUT_DIR = os.getenv("MIRROR_OUTPUT_DIR", "/mnt/paparazzi/mirror_clips")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
