# Generated by Django 4.2.30 on 2026-07-30 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=64, unique=True)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('min_views', models.PositiveIntegerField(default=30000)),
                ('max_age_days', models.PositiveIntegerField(default=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'ordering': ['nome', 'youtube_id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumidorLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=False)),
                ('heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Consumidor de LLM',
                'verbose_name_plural': 'Consumidores de LLM',
            },
        ),
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(blank=True, max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado do sistema',
                'verbose_name_plural': 'Estado do sistema',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=64)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('url_origem', models.URLField(blank=True)),
                ('views', models.BigIntegerField(default=0)),
                ('publicado_origem', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('detectado', 'Detectado'), ('baixando', 'Baixando'), ('processando', 'Processando'), ('processado', 'Processado'), ('postado', 'Postado'), ('erro', 'Erro')], default='detectado', max_length=20)),
                ('versao_sistema', models.CharField(blank=True, max_length=20)),
                ('deteccao', models.JSONField(blank=True, null=True)),
                ('arquivo_local', models.CharField(blank=True, max_length=500)),
                ('arquivo_removido', models.BooleanField(default=False)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.canal')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('tiktok', 'TikTok')], default='tiktok', max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('privacidade', models.CharField(default='SELF_ONLY', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('postando', 'Postando'), ('publicado', 'Publicado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('url_publicada', models.URLField(blank=True)),
                ('postado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.video')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deteccao', 'Detecção'), ('coleta', 'Coleta'), ('processamento', 'Processamento'), ('postagem', 'Postagem'), ('corte', 'Corte')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('rodando', 'Rodando'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.video')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('video_id', 'versao_sistema'), name='uniq_video_por_versao'),
        ),
    ]
