# Generated by Django 4.2.30 on 2026-08-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fn_retencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcricao',
            field=models.TextField(blank=True),
        ),
    ]
