# Generated by Django 4.2.30 on 2026-08-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_transcricao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='video',
            name='uniq_video_por_versao',
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('detectado', 'Detectado'), ('fila_edicao', 'Na fila de edição'), ('baixando', 'Baixando'), ('processando', 'Processando'), ('processado', 'Processado'), ('postado', 'Postado'), ('erro', 'Erro')], default='detectado', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
