# Generated by Django 4.2.30 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fn_retencao_devolve_postado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('postando', 'Postando'), ('publicado', 'Publicado'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
